build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/IMU"
    - PLATFORMIO_PROJECT_DIR: "examples/LEVELER"
    - PLATFORMIO_PROJECT_DIR: "examples/VG_AHRS"

install:
- cmd: git submodule update --init --recursive
- cmd: SET PATH=%PATH%;C:\Python27\Scripts
- cmd: pip install -U https://github.com/platformio/platformio/archive/develop.zip
- cmd: platformio platform install file://.

test_script:
- cmd: platformio run -d %PLATFORMIO_PROJECT_DIR%
